spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:EBUY
    username: hrmanager
    password: hrmanager
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1 from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
management:
  info:
    git:
      mode: full
app:
  workerId: 0
server:
  port: 9090